asp-clinica/Controllers/AtendimentoController.cs
using asp_clinica.Dados;
using asp_clinica.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asp_clinica.Controllers
{
    public class AtendimentoController : Controller
    {
        public void carregaPacientes()
        {
            List<SelectListItem> ag = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdClinica;User=root;pwd=12345678"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbPaciente order by nomePaciente;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    ag.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();
                con.Open();
            }


            ViewBag.paciente = new SelectList(ag, "Value", "Text");
        }

        public void carregaMedico()
        {
            List<SelectListItem> med = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdClinica;User=root;pwd=12345678"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbMedico order by nomeMedico;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    med.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();
                con.Open();
            }


            ViewBag.medico = new SelectList(med, "Value", "Text");
        }

        AcoesAtendimento acAtend = new AcoesAtendimento();
        public ActionResult Index()
        {
            Session["tipo"] = ""; // por enquanto, o cadastro não é necessário
            return View();
        }
        
        public ActionResult CadAtendimento() // abre a tela
        {
            Session["tipo"] = "";
            carregaMedico();
            carregaPacientes();
            return View();
        }
        [HttpPost]
        public ActionResult CadAtendimento(ModelAtendimento cmAtend) // cadastra no banco
        {
            Session["tipo"] = "";
            carregaMedico();
            carregaPacientes();
            acAtend.TestarAgenda(cmAtend);

            if (cmAtend.confAgendamento == "0") 
            {
                ViewBag.msg = "Horário Indisponível! Tente outro.";
            }
            else
            {   cmAtend.codMedico = Request["medico"];
                cmAtend.codPac = Request["paciente"];
                acAtend.InserirAtendimento(cmAtend);
                ViewBag.msg = "Cadastro Realizado com sucesso!";
            }
                
            return View();
        }
    }
}

asp-clinica/Views/Atendimento/CadAtendimento.cshtml
@model asp_clinica.Models.ModelAtendimento


@{
    ViewBag.Title = "cadAtendimento";
}

<h2>Cadastro de Atendimento</h2>



@using (Html.BeginForm("Agenda"))
{
    <label>Agenda</label>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.dataAtend)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.dataAtend, new { htmlAttributes = new { @type = "date" } })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.horaAtend)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.horaAtend, new { htmlAttributes = new { @type = "time" } })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.codPac)
    </div>
    <div class="editor-field">

        @Html.DropDownList("paciente", "Escolha o paciente")

    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.codMedico)
    </div>
    <div class="editor-field">

        @Html.DropDownList("medico", "Escolha o médico")

    </div>

    <br />
    <input type="submit" value="Cadastrar" />
}
<br />
<br />

@ViewBag.msg

    

asp-clinica/Views/Atendimento/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@Html.ActionLink("Cadastro do Atendimento", "CadAtendimento", "Atendimento")